### ISSUE TITLE
diffvg does not compile on cuda11 / latest torch

### ISSUE THREAD

**Issue by pixray** [pixray/diffvg#1]
On 2021/10/08, Colab updated its default PyTorch installation to a version that causes problems with diffvg. The pixray notebooks patched this by rolling back to an older version in dribnet/clipit#18

This issue tracks fixing this in diffvg. The test case would be to run [the pixray Pixel Art demo notebook](https://colab.research.google.com/github/dribnet/clipit/blob/master/demos/PixelDrawer.ipynb) without this rollback applied.

Note that pixray is currently offering a bounty for closing this issue successfully with a pull request - details available in [the pixray discord](https://discord.gg/x2g9TWrNKe).

**Comment by dribnet** [comment]
Note: proposed solution submitted as pull request #2
